#+OPTIONS: toc:nil num:nil author:nil email:nil creator:nil timestamp:nil
#+TITLE: dispswitch

=dispswitch= picks up the window that has focus, and moves it to the
next display monitor it can find, whilst trying to roughly preserve
the monitor-relative position and (if the window is sizeable) size. If
you have multiple monitors, you need this program, and you need it
NOW. It will save you lots of time.

It's designed for use with a hotkey program, such as
[[http://www.autohotkey.com/][AutoHotkey]], so that you can do this with a single keypress.

* download

[[https://github.com/tom-seddon/dispswitch/blob/master/dispswitch_Win32_Release.exe?raw%3Dtrue][dispswitch_Win32_Release.exe]] (from this repo)

* AutoHotkey installation

The official approved AutoHotkey configuration is as follows. Add this
to your AutoHotkey INI file using =Edit This Script= on AutoHotkey's
right click menu. Replace =c:\bin\= with wherever you saved the EXE
to.

#+BEGIN_EXAMPLE
#a::Run c:\bin\dispswitch_Win32_Release.exe
#+END_EXAMPLE

Use =Reload This Script= on AutoHotkey's right click menu to refresh
everything. Then hold Windows key and tap A to move the current window
from one monitor to another.
